-- 002_seed_scenarios.sql
-- Заполнить таблицу scenario_definitions базовыми сценариями.

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('site.A','site','A','Сайт — передача исполнителю','{"key": "site.A", "type": "site", "mode": "A", "name_ru": "Сайт — передача исполнителю", "required_data_keys": ["project_profile", "audience", "offer", "competitors", "references"], "steps": [{"scenario_key": "site.A.01.profile", "order": 10, "title_ru": "Уточнение проекта и профиль", "description_ru": "Собираем вводные и фиксируем, что делаем и для кого.", "acceptance_ru": "Профиль заполнен: продукт, цель, ЦА, метрики, ограничения, интеграции.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай 10 вопросов.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}"}, {"scenario_key": "site.A.02.structure", "order": 20, "title_ru": "Структура лендинга", "description_ru": "Делаем 2 структуры: конверсия и доверие.", "acceptance_ru": "Есть 2 структуры, по каждому блоку: цель, тезис, CTA, доказательство.", "required_fields": ["project_profile", "audience", "offer"], "ai_tool_default": "gpt", "prompt_template_ru": "Сделай 2 структуры лендинга (RU): A) Конверсия B) Доверие.\nКонтекст:\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nТребования: 8–14 блоков, у каждого цель/тезис/CTA/доказательство."}, {"scenario_key": "site.A.03.copy", "order": 30, "title_ru": "Тексты по блокам", "description_ru": "Пишем hero, блоки, CTA, FAQ.", "acceptance_ru": "Тексты готовы: 3 hero + блоки + FAQ 10–15 + CTA 5.", "required_fields": ["project_profile", "audience", "offer"], "ai_tool_default": "claude", "prompt_template_ru": "Напиши тексты лендинга (RU): 3 hero (заголовок+подзаголовок+CTA), тексты по секциям, FAQ 10–15, CTA 5.\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}"}, {"scenario_key": "site.A.04.spec", "order": 40, "title_ru": "ТЗ для дизайна/вёрстки", "description_ru": "Формализуем, чтобы исполнитель собрал без созвонов.", "acceptance_ru": "Есть ТЗ: секции, компоненты, форма, интеграции, аналитика, адаптив, чеклист приёмки.", "required_fields": ["project_profile", "references"], "ai_tool_default": "claude", "prompt_template_ru": "Собери ТЗ для дизайнера/верстальщика (RU).\nПрофиль: {{project_profile.full}}\nРеференсы: {{references.full}}\nОбязательно: секции, адаптив, форма (поля/валидация), интеграции, события view/click/submit, критерии приёмки."}, {"scenario_key": "site.A.05.handoff", "order": 50, "title_ru": "Пакет передачи", "description_ru": "Собираем пакет, который отдаёшь одним сообщением.", "acceptance_ru": "Пакет готов: профиль, структура, тексты, ТЗ, референсы, чеклист.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери «Пакет передачи» (RU) в одном сообщении: профиль, структура, тексты, ТЗ, референсы, чеклист приёмки. Коротко и структурно."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('site.B','site','B','Сайт — готовый (деплой + домен + SSL + форма + аналитика)','{"key": "site.B", "type": "site", "mode": "B", "name_ru": "Сайт — готовый (деплой + домен + SSL + форма + аналитика)", "required_data_keys": ["project_profile", "audience", "offer", "competitors", "references", "tracking"], "steps": [{"scenario_key": "site.B.01.profile", "order": 10, "title_ru": "Уточнение проекта и профиль", "description_ru": "Собираем вводные.", "acceptance_ru": "Профиль заполнен.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU) и предложи стек: static или Next.js.\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}"}, {"scenario_key": "site.B.02.copy", "order": 20, "title_ru": "Тексты лендинга", "description_ru": "Готовим тексты.", "acceptance_ru": "Готовы: 3 hero, секции, FAQ 10–15, CTA 5.", "required_fields": ["project_profile", "audience", "offer"], "ai_tool_default": "claude", "prompt_template_ru": "Напиши тексты лендинга (RU): 3 hero, секции, FAQ 10–15, CTA 5.\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}"}, {"scenario_key": "site.B.03.build", "order": 30, "title_ru": "Сборка сайта (код)", "description_ru": "Генерируем проект сайта по текстам и структуре.", "acceptance_ru": "Есть проект сайта + README.", "required_fields": ["project_profile", "references"], "ai_tool_default": "gemini", "prompt_template_ru": "Собери проект сайта (код) по ТЗ (RU): структура проекта, адаптив, SEO минимум, форма (заглушка), README.\nПрофиль: {{project_profile.full}}\nРеференсы: {{references.full}}"}, {"scenario_key": "site.B.04.deploy", "order": 40, "title_ru": "Деплой + домен + SSL", "description_ru": "Выводим сайт по URL и подключаем домен.", "acceptance_ru": "Сайт доступен по домену с SSL.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Дай пошаговый деплой на Vercel/Netlify + подключение домена и SSL. Укажи типичные ошибки и как проверить."}, {"scenario_key": "site.B.05.analytics", "order": 50, "title_ru": "Минимальная аналитика", "description_ru": "UTM + события view/click/submit.", "acceptance_ru": "События пишутся и проверены.", "required_fields": ["tracking"], "ai_tool_default": "gpt", "prompt_template_ru": "Собери минимум аналитики (RU): UTM схема + события view/click/submit + как проверить.\nКонтекст: {{tracking.full}}"}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('bot.A','bot','A','BOT — режим A','{"key": "bot.A", "type": "bot", "mode": "A", "name_ru": "BOT — режим A", "required_data_keys": ["project_profile", "audience", "offer"], "steps": [{"scenario_key": "bot.A.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "bot.A.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "bot.A.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('bot.B','bot','B','BOT — режим B','{"key": "bot.B", "type": "bot", "mode": "B", "name_ru": "BOT — режим B", "required_data_keys": ["project_profile", "audience", "offer"], "steps": [{"scenario_key": "bot.B.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "bot.B.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "bot.B.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('ads.A','ads','A','ADS — режим A','{"key": "ads.A", "type": "ads", "mode": "A", "name_ru": "ADS — режим A", "required_data_keys": ["project_profile", "audience", "offer", "tracking"], "steps": [{"scenario_key": "ads.A.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "ads.A.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "ads.A.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('ads.B','ads','B','ADS — режим B','{"key": "ads.B", "type": "ads", "mode": "B", "name_ru": "ADS — режим B", "required_data_keys": ["project_profile", "audience", "offer", "tracking"], "steps": [{"scenario_key": "ads.B.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "ads.B.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "ads.B.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('strategy.A','strategy','A','STRATEGY — режим A','{"key": "strategy.A", "type": "strategy", "mode": "A", "name_ru": "STRATEGY — режим A", "required_data_keys": ["project_profile", "audience", "offer", "competitors"], "steps": [{"scenario_key": "strategy.A.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "strategy.A.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "strategy.A.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('strategy.B','strategy','B','STRATEGY — режим B','{"key": "strategy.B", "type": "strategy", "mode": "B", "name_ru": "STRATEGY — режим B", "required_data_keys": ["project_profile", "audience", "offer", "competitors"], "steps": [{"scenario_key": "strategy.B.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "strategy.B.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "strategy.B.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('market.A','market','A','MARKET — режим A','{"key": "market.A", "type": "market", "mode": "A", "name_ru": "MARKET — режим A", "required_data_keys": ["project_profile", "competitors", "audience"], "steps": [{"scenario_key": "market.A.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "market.A.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "market.A.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('market.B','market','B','MARKET — режим B','{"key": "market.B", "type": "market", "mode": "B", "name_ru": "MARKET — режим B", "required_data_keys": ["project_profile", "competitors", "audience"], "steps": [{"scenario_key": "market.B.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "market.B.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "market.B.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('product.A','product','A','PRODUCT — режим A','{"key": "product.A", "type": "product", "mode": "A", "name_ru": "PRODUCT — режим A", "required_data_keys": ["project_profile", "audience", "offer"], "steps": [{"scenario_key": "product.A.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "product.A.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "product.A.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('product.B','product','B','PRODUCT — режим B','{"key": "product.B", "type": "product", "mode": "B", "name_ru": "PRODUCT — режим B", "required_data_keys": ["project_profile", "audience", "offer"], "steps": [{"scenario_key": "product.B.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "product.B.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "product.B.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('software.A','software','A','SOFTWARE — режим A','{"key": "software.A", "type": "software", "mode": "A", "name_ru": "SOFTWARE — режим A", "required_data_keys": ["project_profile", "audience", "offer"], "steps": [{"scenario_key": "software.A.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "software.A.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "software.A.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;

insert into public.scenario_definitions(key,type,mode,name_ru,definition_json)
values ('software.B','software','B','SOFTWARE — режим B','{"key": "software.B", "type": "software", "mode": "B", "name_ru": "SOFTWARE — режим B", "required_data_keys": ["project_profile", "audience", "offer"], "steps": [{"scenario_key": "software.B.01.profile", "order": 10, "title_ru": "Уточнение и профиль", "description_ru": "Собираем вводные и фиксируем профиль.", "acceptance_ru": "Профиль заполнен, есть ясность по задаче.", "required_fields": [], "ai_tool_default": "gpt", "prompt_template_ru": "Собери профиль проекта (RU). Если данных мало — задай вопросы.\n\nПрофиль: {{project_profile.full}}\nЦА: {{audience.full}}\nОффер: {{offer.full}}\nКонкуренты: {{competitors.short}}"}, {"scenario_key": "software.B.02.plan", "order": 20, "title_ru": "План работ", "description_ru": "Декомпозиция в шаги + риски + критерии.", "acceptance_ru": "Есть план и критерии приёмки.", "required_fields": ["project_profile"], "ai_tool_default": "gpt", "prompt_template_ru": "Составь план работ (RU) на 7–14 дней.\nКонтекст: {{project_profile.full}}\nФормат: таблица (шаг, результат, метрика, риск)."}, {"scenario_key": "software.B.03.package", "order": 30, "title_ru": "Итоговый пакет", "description_ru": "Собираем итог: что готово и что дальше.", "acceptance_ru": "Есть итоговый пакет и next steps.", "required_fields": [], "ai_tool_default": "claude", "prompt_template_ru": "Собери итоговый пакет (RU):\n- что сделано\n- что осталось\n- риски\n- следующий шаг."}]}'::jsonb)
on conflict (key) do update set definition_json=excluded.definition_json, name_ru=excluded.name_ru;
